display_name: PicGuard
icon: logo/logo-512.png
summary: Your pictures, your signature.
group: Application/Emulator
vendor: kjxbyz
packager: kjxbyz
packagerEmail: hello@kjxbyz.com
license: GPL-3.0-only
url: https://github.com/picguard/picguard
build_arch: x86_64

metainfo: linux/shared/picguard.metainfo.xml

keywords:
  - PicGuard
  - Watermark
  - Assistant
  - Watermark Assistant

generic_name: PicGuard

categories:
  - Utility

startup_notify: true
